config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get '/user/:id', to: 'users#set_user', as: :user
  devise_for :users, :controllers => {
  registrations: 'registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root "events#index"
  resources :events do
    member do
      get 'accept_invitation'
      get 'cancel_invitation'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  # looks for the foreign key name after the association (creator_id)
  validates :title, :description, :date, :location, presence: true
  belongs_to :creator, class_name: "User"
  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations

  scope :past, -> { where('date < ?', Date.today).order(date: :desc) }
  scope :future, -> { where('date > ?', Date.today).order(:date) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :creator_events, foreign_key: "creator_id", class_name: "Event"
  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: %i[ show edit update destroy ]
  def index
    @events = Event.all
  end

  def new
    # @event = Event.new
    @event = current_user.creator_events.build
  end

  def show
  end

  def edit
  end

  def create
    # the build method creates the event with the user's id prepopulated
    @event = current_user.creator_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_url, notice: "Your event was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Your event was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
    end
  end

  def accept_invitation
    @event = Event.find(params[:id])
    if @event.attendees.include?(current_user)
      redirect_to @event, notice: "You are already on the list"
    else
      @event.attendees << current_user
      redirect_to @event
    end
  end

  def cancel_invitation
    @event = Event.find(params[:id])
    @event.attendees.delete(current_user)
    redirect_to @event, notice: "You are no longer attending this event"
  end


  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :date, :location, :description, :creator_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

    def sign_up_params
      params.require(:user).permit(:email, :password, :name)
    end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def set_user
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div>
  <p>
    <strong>Title:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Creator:</strong>
    <%= User.find(event.creator_id).name %>
  </p>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="field form-group">
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div class="field form-group">
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div class="field form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, size: "40x8" %>
  </div>

<!--   <div class="field form-group">
    <%= form.number_field :creator_id, id: :event_creator_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit an Event</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<div class="row mb-4">
  <div class="col">
    <h1>Upcoming Events</h1>
  </div>
  <div>
    <%= link_to 'Create Event', new_event_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

<div class="row mb-5">
  <% Event.future.each do |event| %>
  <div class="col-md-4 mb-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          <%= event.title %>
        </h5>
        <h6 class="small text-muted"><%= event.date.strftime("%B %-d, %Y") %></h6>
        <h6 class="small text-muted"><%= event.location %></h6>
        <p class="card-text d-inline-block "><%= event.description.truncate(110) %></p>
        <div><%= link_to "see more", event, class: "btn btn-outline-primary btn-block"%></div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<h4 class="text-muted">PAST EVENTS</h4>
<div class="row">
  <% Event.past.each do |event| %>
  <div class="col-md-4 mb-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          <%= event.title %>
        </h5>
        <h6 class="small text-muted"><%= event.date.strftime("%B %-d, %Y") %></h6>
        <h6 class="small text-muted"><%= event.location %></h6>
        <p class="card-text d-inline-block "><%= event.description.truncate(110) %></p>
        <div><%= link_to "see more", event, class: "btn btn-outline-primary btn-block"%></div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Create an Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<% if @event.date < Time.now %>
  <div class="alert alert-warning text-center" role="alert">Event registration is now closed.</div>
<% end %>


<div class="card">
  <div class="card-header col">
    <h1><%= @event.title %></h1>
    <p class="text-muted">Event Created by <%= User.find(@event.creator_id).name %></p>
    <p class="text-muted">@ <%= @event.date.strftime("%B %-d, %Y at %l:%M %p") %></p>
    <p class="text-muted">Location: <%= @event.location %></p>
  </div>
  <div class="card-body">
    <p class="card-text"><%= @event.description %></p>
    <div class>
      <% if current_user == @event.creator %>
        <%= link_to 'Edit', edit_event_path, class: "btn btn-primary mb-1" %>
        <%= button_to 'Delete', event_path, method: :delete, class: "btn btn-primary" %>
      <% elsif @event.attendees.include?(current_user) %>
        <%= link_to 'Cancel Invite', cancel_invitation_event_path, class: "btn btn-primary" %>
      <% else %>
        <%= link_to 'Join Event', accept_invitation_event_path, class: "btn btn-primary" unless @event.date < Time.now %>
      <% end %>
    </div>
  </div>
</div>

<h5 class=" text-muted mb-1">Lists of Attendees</h4>
<% if @event.attendees.empty? %>
<ul class="list-group list-group-flush">
  <li class="list-group-item text-muted">None</li>
</ul>
<% else %>
  <ul class="list-group list-group-flush">
    <% @event.attendees.each do |attendee| %>
    <li class="list-group-item text-muted"> <%= attendee.name %> </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_nav.html.erb
  <div class="container">
    <%= link_to 'Private Events', root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to current_user.name, user_path(current_user), class: "nav-link disabled" %>
          </li>
        <% end %>
      </ul>
      <span class="navbar-nav">
        <% if user_signed_in? %>
          <%= link_to 'My Events', user_path(current_user), class: "nav-item nav-link" %>
          <%= link_to 'Edit Account', edit_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
        <% else %>
            <%= link_to 'Log In', user_session_path, class: "nav-item nav-link" %>
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-item nav-link" %>
        <% end %>
      </span>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg" style="background-color: #9cc3c9">
  <%= render 'layouts/nav' %>
</nav>
  <div class="container">
    <p class="notice" style="color: green"><%= notice %></p>
    <p class="alert" style="color: red"><%= alert %></p>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/set_user.html.erb
<h1 class="mb-4"> Your Events</h1>

<div class="col">
  <div class="row-md mb-4">
    <p>EVENTS CREATED</p>
  </div>
</div>

<div class="row mb-5">
  <% @user.creator_events.each do |event| %>

  <div class="col-md-4 mb-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          <%= event.title %>
        </h5>
        <h6 class="small text-muted"><%= event.date.strftime("%B %-d, %Y") %></h6>
        <h6 class="small text-muted"><%= event.location %></h6>
        <p class="card-text d-inline-block "><%= event.description.truncate(110) %></p>
        <div><%= link_to "see more", event, class: "btn btn-outline-primary btn-block"%></div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<div class="col">
  <div class="row-md mb-4">
    <p> EVENTS ATTENDED</p>
  </div>
</div>

<div class="row mb-5">
  <% @user.attended_events.each do |event| %>

  <div class="col-md-4 mb-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          <%= event.title %>
        </h5>
        <h6 class="small text-muted"><%= event.date.strftime("%B %-d, %Y") %></h6>
        <h6 class="small text-muted"><%= event.location %></h6>
        <p class="card-text d-inline-block "><%= event.description.truncate(110) %></p>
        <div><%= link_to "see more", event, class: "btn btn-outline-primary btn-block"%></div>
      </div>
    </div>
  </div>
  <% end %>
</div>